Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -60,7 +60,6 @@ jobs:
 
       - name: Test
         run: |
-
           java -cp jaylib-$RAYLIB_VERSION.jar:jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
           cat /tmp/output
           if grep -q "INFO: Initializing raylib" /tmp/output; then
@@ -78,6 +77,8 @@ jobs:
 
   build-linux-32bit:
     runs-on: ubuntu-latest
+    env:
+      RAYLIB_PLATFORM: linux-x86
     container:
       image: electronstudio/ubuntu16-modern:i386
       options: --user root
@@ -121,12 +122,21 @@ jobs:
           make install
 
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: linux-x86
         run: |
           ./build-java.sh
           ./build-native.sh
           ./build-docs.sh
+
+      - name: Test
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar:jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload jar
         uses: actions/upload-artifact@v4
@@ -136,6 +146,8 @@ jobs:
 
   build-linux-arm64:
     runs-on: ubuntu-22.04-arm
+    env:
+      RAYLIB_PLATFORM: linux-arm64
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
@@ -168,12 +180,21 @@ jobs:
           sudo make install
 
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: linux-arm64
         run: |
           ./build-java.sh
           ./build-native.sh
           ./build-docs.sh
+
+      - name: Test
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar:jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload jar
         uses: actions/upload-artifact@v4
@@ -184,7 +205,8 @@ jobs:
   build-mac-intel:
     runs-on: macos-15-intel
     env:
-      MACOSX_DEPLOYMENT_TARGET: 11.0
+      MACOSX_DEPLOYMENT_TARGET: 10.14
+      RAYLIB_PLATFORM: macosx-x86_64
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -205,7 +227,7 @@ jobs:
           sed -i '' 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
           mkdir build
           cd build
-          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF -DSDL_TEST_LIBRARY=OFF -DSDL_TESTS=OFF -DSDL_RENDER=OFF -DSDL_HAPTIC=OFF
+          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF -DSDL_TEST_LIBRARY=OFF -DSDL_TESTS=OFF -DSDL_RENDER=OFF -DSDL_HAPTIC=OFF
           cmake --build . --config Release
           sudo cmake --install .
 
@@ -214,17 +236,26 @@ jobs:
           cd raylib
           mkdir build
           cd build
-          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" -DBUILD_EXAMPLES=OFF -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
+          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" -DBUILD_EXAMPLES=OFF -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
           make -j2
           sudo make install
 
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: macosx-x86_64
         run: |
           ./build-java.sh
           ./build-native.sh
 
+      - name: Test
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar:jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
+          
       - name: Upload jar
         uses: actions/upload-artifact@v4
         with:
