Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -255,7 +255,7 @@ jobs:
             echo "Failed"
             exit 1
           fi
-          
+
       - name: Upload jar
         uses: actions/upload-artifact@v4
         with:
@@ -263,9 +263,10 @@ jobs:
           path: ./*macosx-x86_64*.jar
 
   build-mac-arm64:
-    runs-on: macos-14
+    runs-on: macos-26
     env:
       MACOSX_DEPLOYMENT_TARGET: 11.0
+      RAYLIB_PLATFORM: macosx-arm64
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -300,11 +301,20 @@ jobs:
           sudo make install
 
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: macosx-arm64
         run: |
           ./build-java.sh
           ./build-native.sh
+
+      - name: Test
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar:jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload jar
         uses: actions/upload-artifact@v4
@@ -314,6 +324,8 @@ jobs:
 
   build-windows:
     runs-on: windows-2022
+    env:
+      RAYLIB_PLATFORM: windows-x86_64
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -358,8 +370,6 @@ jobs:
 
       - uses: ilammy/msvc-dev-cmd@v1
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: windows-x86_64
         run: |
           build-windows.bat
         shell: cmd
@@ -372,6 +382,8 @@ jobs:
 
   build-windows32:
     runs-on: windows-2022
+    env:
+      AYLIB_PLATFORM: windows-x86
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -420,11 +432,33 @@ jobs:
         with:
           arch: x86
       - name: Build jaylib
-        env:
-          RAYLIB_PLATFORM: windows-x86
         run: |
           build-windows.bat
         shell: cmd
+
+      - name: Test
+        shell: bash
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar;jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
+
+      - name: Test
+        shell: bash
+        run: |
+          java -cp jaylib-$RAYLIB_VERSION.jar;jaylib-natives-$RAYLIB_PLATFORM-$RAYLIB_VERSION.jar com.raylib.Test >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload jar
         uses: actions/upload-artifact@v4
