update to fixed raylib

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -64,6 +64,18 @@ jobs:
           ./build-native.sh
           ./build-docs.sh
 
+      - name: Test
+        run: |
+
+          ${{ matrix.python-version }} -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
+
       - name: Upload jar
         uses: actions/upload-artifact@v4
         with:
